# Generated by Django 3.1.1 on 2021-06-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, unique=True, verbose_name='作者')),
                ('sex', models.BooleanField(blank=True, verbose_name='性别')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('introduce', models.CharField(default='这个作者很懒，什么都没有留下 *_^_*!', max_length=200, null=True, verbose_name='个人简介')),
            ],
            options={
                'db_table': 'tb_author',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20, unique=True, verbose_name='类别')),
            ],
            options={
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20, unique=True, verbose_name='标签')),
            ],
            options={
                'db_table': 'tb_tag',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='文章标题')),
                ('description', models.CharField(default='暂无相关描述', max_length=100, verbose_name='描述')),
                ('content', models.TextField(verbose_name='内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布期日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.category')),
                ('tag', models.ManyToManyField(to='myblog.Tag')),
            ],
            options={
                'db_table': 'tb_article',
                'ordering': ['pub_date'],
            },
        ),
    ]
